<?php

/**
 * Seeder for symptoms table
 *
 * PHP version 7.2.19
 *
 * @category Seeder
 * @package  Database/seeders
 * @author   Group7s <dcs@jfn.ac.lk>
 * @license  GNU General Public License (GPL)
 * @link     https://github.com/dcs-university-of-jaffna/PIMS.git
 */

use Illuminate\Database\Seeder;

/**
 * Seeder class for symptoms table
 *
 * PHP version 7.2.19
 *
 * Use this seeder to seed symptoms table
 *
 *           **** Include all symptom details ****
 *
 * @category Seeder
 * @package  Database/seeders
 * @author   Group7s <dcs@jfn.ac.lk>
 * @license  GNU General Public License (GPL)
 * @link     https://github.com/dcs-university-of-jaffna/PIMS.git
 */

class SymptomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('symptoms')->insert(
            [
                ['id' => 1, 'name' => 'abdominal pain'],
                ['id' => 2, 'name' => 'acute renal failure'],
                ['id' => 3, 'name' => 'agitation'],
                ['id' => 4, 'name' => 'alopecia'],
                ['id' => 5, 'name' => 'anaphylaxis'],
                ['id' => 6, 'name' => 'anuria'],
                ['id' => 7, 'name' => 'anxiety'],
                ['id' => 8, 'name' => 'aphonia'],
                ['id' => 9, 'name' => 'atrial and ventricular ectopics'],
                ['id' => 10, 'name' => 'bleeding manifestations'],
                ['id' => 11, 'name' => 'blepharospasm'],
                ['id' => 12, 'name' => 'blisters of oral mucosa'],
                ['id' => 13, 'name' => 'bradycardia'],
                ['id' => 14, 'name' => 'bronchospasm'],
                ['id' => 15, 'name' => 'bulging eyes'],
                ['id' => 16, 'name' => 'burning sensation'],
                ['id' => 17, 'name' => 'burning sensation of mouth'],
                ['id' => 18, 'name' => 'cardiac arrhythmias'],
                ['id' => 19, 'name' => 'circumoral paresthesia'],
                ['id' => 20, 'name' => 'CNS depression'],
                ['id' => 21, 'name' => 'coma'],
                ['id' => 22, 'name' => 'combative'],
                ['id' => 23, 'name' => 'confusion'],
                ['id' => 24, 'name' => 'conjunctival chemosis'],
                ['id' => 25, 'name' => 'convulsion'],
                ['id' => 26, 'name' => 'corneal abrasions'],
                ['id' => 27, 'name' => 'cough'],
                ['id' => 28, 'name' => 'cramps'],
                ['id' => 29, 'name' => 'cyanosis'],
                ['id' => 30, 'name' => 'cycloplegia'],
                ['id' => 31, 'name' => 'dehydration'],
                ['id' => 32, 'name' => 'delirium'],
                ['id' => 33, 'name' => 'demyelination'],
                ['id' => 34, 'name' => 'diarrhoea'],
                ['id' => 35, 'name' => 'diarrhoea with blood and mucus'],
                ['id' => 36, 'name' => 'diarrhoea watery'],
                ['id' => 37, 'name' => 'dilation of pupils'],
                ['id' => 38, 'name' => 'disorientation'],
                ['id' => 39, 'name' => 'disturbance of consciousness'],
                ['id' => 40, 'name' => 'dizziness'],
                ['id' => 41, 'name' => 'drowsiness'],
                ['id' => 42, 'name' => 'dry mouth'],
                ['id' => 43, 'name' => 'dryness of mucous membrane'],
                ['id' => 44, 'name' => 'dysphagia'],
                ['id' => 45, 'name' => 'ecg abnormalities'],
                ['id' => 46, 'name' => 'electrolytes imbalance'],
                ['id' => 47, 'name' => 'epigastric pain'],
                ['id' => 48, 'name' => 'erythema'],
                ['id' => 49, 'name' => 'extensor spasms'],
                ['id' => 50, 'name' => 'exudate'],
                ['id' => 51, 'name' => 'eye inflammation'],
                ['id' => 52, 'name' => 'eyelid oedema'],
                ['id' => 53, 'name' => 'facial oedema'],
                ['id' => 54, 'name' => 'fever'],
                ['id' => 55, 'name' => 'fits'],
                ['id' => 56, 'name' => 'fits of crying'],
                ['id' => 57, 'name' => 'flushing of face'],
                ['id' => 58, 'name' => 'gastroenteritis'],
                ['id' => 59, 'name' => 'haematemesis'],
                ['id' => 60, 'name' => 'haematuria'],
                ['id' => 61, 'name' => 'haemorrhagic gastritis'],
                ['id' => 62, 'name' => 'haemorrhagic gastroententis'],
                ['id' => 63, 'name' => 'hallucinogenic effects'],
                ['id' => 64, 'name' => 'heart block'],
                ['id' => 65, 'name' => 'hepatic insufficiency'],
                ['id' => 66, 'name' => 'hepatic necrosis'],
                ['id' => 67, 'name' => 'hepatotoxicity'],
                ['id' => 68, 'name' => 'hyperpnoea'],
                ['id' => 69, 'name' => 'hyperreflexia'],
                ['id' => 70, 'name' => 'hypersensitivity reactions'],
                ['id' => 71, 'name' => 'hyperthermia'],
                ['id' => 72, 'name' => 'hypocalcemia'],
                ['id' => 73, 'name' => 'hypoglycemia'],
                ['id' => 74, 'name' => 'hypotension'],
                ['id' => 75, 'name' => 'hypovolaemia'],
                ['id' => 76, 'name' => 'hypovolemic shock'],
                ['id' => 77, 'name' => 'hypoxaemia'],
                ['id' => 78, 'name' => 'impaired articulation'],
                ['id' => 79, 'name' => 'intense pain'],
                ['id' => 80, 'name' => 'junctional rhythms'],
                ['id' => 81, 'name' => 'laryngeal oedema'],
                ['id' => 82, 'name' => 'malaise'],
                ['id' => 83, 'name' => 'malena'],
                ['id' => 84, 'name' => 'metabolic acidosis'],
                ['id' => 85, 'name' => 'muscle twitching'],
                ['id' => 86, 'name' => 'mydriasis'],
                ['id' => 87, 'name' => 'myocarditis'],
                ['id' => 88, 'name' => 'myoglobinuria'],
                ['id' => 89, 'name' => 'nausea'],
                ['id' => 90, 'name' => 'necrosis'],
                ['id' => 91, 'name' => 'necrotic oesophagitis'],
                ['id' => 92, 'name' => 'necrotising enteritis'],
                ['id' => 93, 'name' => 'numbness of mouth'],
                ['id' => 94, 'name' => 'oedema of lips'],
                ['id' => 95, 'name' => 'oedema of salivary glands'],
                ['id' => 96, 'name' => 'oedema of throat'],
                ['id' => 97, 'name' => 'oedema of tongue'],
                ['id' => 98, 'name' => 'oliguria'],
                ['id' => 99, 'name' => 'opisthotonus'],
                ['id' => 100, 'name' => 'oral cavity irritation'],
                ['id' => 101, 'name' => 'pain'],
                ['id' => 102, 'name' => 'painful convulsions'],
                ['id' => 103, 'name' => 'pallor'],
                ['id' => 104, 'name' => 'pancreatitis'],
                ['id' => 105, 'name' => 'papilloedema'],
                ['id' => 106, 'name' => 'photophobia'],
                ['id' => 107, 'name' => 'polydipsia'],
                ['id' => 108, 'name' => 'polyneuropathy'],
                ['id' => 109, 'name' => 'profuse salivation'],
                ['id' => 110, 'name' => 'pruritus'],
                ['id' => 111, 'name' => 'psychomotor disturbances'],
                ['id' => 112, 'name' => 'pulmonary infiltration'],
                ['id' => 113, 'name' => 'pulmonary oedema'],
                ['id' => 114, 'name' => 'renal failure'],
                ['id' => 115, 'name' => 'respiratory depression'],
                ['id' => 116, 'name' => 'respiratory distress'],
                ['id' => 117, 'name' => 'respiratory failure'],
                ['id' => 118, 'name' => 'restlessness'],
                ['id' => 119, 'name' => 'retinal haemorrhage'],
                ['id' => 120, 'name' => 'retinopathy'],
                ['id' => 121, 'name' => 'rhabdomyolysis'],
                ['id' => 122, 'name' => 'right iliac fossa tenderness'],
                ['id' => 123, 'name' => 'risus sardonicus'],
                ['id' => 124, 'name' => 'salivation'],
                ['id' => 125, 'name' => 'seizure'],
                ['id' => 126, 'name' => 'shock'],
                ['id' => 127, 'name' => 'sinoatrial block'],
                ['id' => 128, 'name' => 'sinus bradycardia'],
                ['id' => 129, 'name' => 'slow pulse'],
                ['id' => 130, 'name' => 'sweating'],
                ['id' => 131, 'name' => 'swelling'],
                ['id' => 132, 'name' => 'tachycardia'],
                ['id' => 133, 'name' => 'talkativeness'],
                ['id' => 134, 'name' => 'tender liver'],
                ['id' => 135, 'name' => 'tenderness'],
                ['id' => 136, 'name' => 'thirst'],
                ['id' => 137, 'name' => 'tightness of chest'],
                ['id' => 138, 'name' => 'tremor'],
                ['id' => 139, 'name' => 'trismus'],
                ['id' => 140, 'name' => 'urticaria'],
                ['id' => 141, 'name' => 'ventricular arrhythmia'],
                ['id' => 142, 'name' => 'ventricular ectopics'],
                ['id' => 143, 'name' => 'ventricular fibrillation'],
                ['id' => 144, 'name' => 'vomiting'],
                ['id' => 145, 'name' => 'watery eyes'],
                ['id' => 146, 'name' => 'weakness'],
                ['id' => 147, 'name' => 'yellow vision'],
                ['id' => 148, 'name' => 'hallucination'],
                ['id' => 149, 'name' => 'imitability'],
                ['id' => 150, 'name' => 'insomnia'],
                ['id' => 151, 'name' => 'dryness of mouth'],
                ['id' => 152, 'name' => 'intracerebral'],
                ['id' => 153, 'name' => 'faval flushing'],
                ['id' => 154, 'name' => 'swearing'],
                ['id' => 155, 'name' => 'hallucinations'],
                ['id' => 156, 'name' => 'paranoia'],
                ['id' => 157, 'name' => 'hypertension'],
                ['id' => 158, 'name' => 'cardiac dysrhythmias (VF)'],
                ['id' => 159, 'name' => 'hyperpyrexia'],
                ['id' => 160, 'name' => 'subarachnoid '],
                ['id' => 161, 'name' => 'violence'],
                ['id' => 162, 'name' => 'subdural haemorrhage'],
                ['id' => 163, 'name' => 'convulsions'],
                ['id' => 164, 'name' => 'sinus tachycardia'],
                ['id' => 165, 'name' => 'burning pain'],
                ['id' => 166, 'name' => 'serum sickness'],
                ['id' => 167, 'name' => 'local necrosis'],
                ['id' => 168, 'name' => 'scarlatiniform rash'],
                ['id' => 169, 'name' => 'haemoglobinuria'],
                ['id' => 170, 'name' => 'coagulopathy'],
                ['id' => 171, 'name' => 'cramping truncal pain'],
                ['id' => 172, 'name' => 'muscle spasm'],
                ['id' => 173, 'name' => 'headache'],
                ['id' => 174, 'name' => 'tachypnoea'],
                ['id' => 175, 'name' => 'hyperaesthesia'],
                ['id' => 176, 'name' => 'ptosis'],
                ['id' => 177, 'name' => 'redness'],
                ['id' => 178, 'name' => 'stinging'],
                ['id' => 179, 'name' => 'throbbing'],
                ['id' => 180, 'name' => 'shooting pain'],
                ['id' => 181, 'name' => 'rash'],
                ['id' => 182, 'name' => 'paraesthesia'],
                ['id' => 183, 'name' => 'anaphylactoid'],
                ['id' => 184, 'name' => 'muscle pain'],
                ['id' => 185, 'name' => 'myalgia'],
                ['id' => 186, 'name' => 'arthralgia'],
                ['id' => 187, 'name' => 'local oedema'],
                ['id' => 188, 'name' => 'hemolysis'],
                ['id' => 189, 'name' => 'erythematous papular lesion'],
                ['id' => 190, 'name' => 'supraventricular'],
                ['id' => 191, 'name' => 'ventricular dysrhythmias'],
                ['id' => 192, 'name' => 'desquamation'],
                ['id' => 193, 'name' => 'chills'],
                ['id' => 194, 'name' => 'orthostatic hypotension'],
                ['id' => 195, 'name' => 'constipation'],
                ['id' => 196, 'name' => 'dilated pupils'],
                ['id' => 197, 'name' => 'ataxia'],
                ['id' => 198, 'name' => 'poorly reactive'],
                ['id' => 199, 'name' => 'hot skin'],
                ['id' => 200, 'name' => 'dry skin'],
                ['id' => 201, 'name' => 'ecchymosis'],
                ['id' => 202, 'name' => 'flushed skin'],
                ['id' => 203, 'name' => 'urinary retention'],
                ['id' => 204, 'name' => 'blurred vision'],
                ['id' => 205, 'name' => 'violent behavior'],
                ['id' => 206, 'name' => 'sonnolenza'],
                ['id' => 207, 'name' => 'lymphangitis'],
                ['id' => 208, 'name' => 'blisters'],
                ['id' => 209, 'name' => 'facial muscle weakness'],
                ['id' => 210, 'name' => 'areflexia'],
                ['id' => 211, 'name' => 'respiratory paralysis'],
                ['id' => 212, 'name' => 'visual disturbances'],
                ['id' => 213, 'name' => 'double vision'],
                ['id' => 214, 'name' => 'external ophthalmoplegia'],
                ['id' => 215, 'name' => 'inability to concentrate'],
                ['id' => 216, 'name' => 'abdominal cramps'],
                ['id' => 217, 'name' => 'productive cough'],
                ['id' => 218, 'name' => 'tenesmus'],
                ['id' => 219, 'name' => 'rhinorrhoea'],
                ['id' => 220, 'name' => 'lachrymation'],
                ['id' => 221, 'name' => 'small/pinpoint pupil'],
                ['id' => 222, 'name' => 'rhonchi'],
                ['id' => 223, 'name' => 'dyspnoea'],
                ['id' => 224, 'name' => 'urinary frequency'],
                ['id' => 225, 'name' => 'incontinence'],
                ['id' => 226, 'name' => 'cardiac arrhythmia'],
                ['id' => 227, 'name' => 'conduction defects'],
                ['id' => 228, 'name' => 'incoordination'],
                ['id' => 229, 'name' => 'paralysis'],
                ['id' => 230, 'name' => 'cranial nerve palsies'],
                ['id' => 231, 'name' => 'general weakness'],
                ['id' => 232, 'name' => 'giddiness'],
                ['id' => 233, 'name' => 'hyperglycemia'],
                ['id' => 234, 'name' => 'acute pancreatitis'],
                ['id' => 235, 'name' => 'delayed weakness'],
                ['id' => 236, 'name' => 'burning sensation of tongue'],
                ['id' => 237, 'name' => 'hyporeflexia'],
                ['id' => 238, 'name' => 'myotonia'],
                ['id' => 239, 'name' => 'miosis'],
                ['id' => 240, 'name' => 'nystagmus'],
                ['id' => 241, 'name' => 'hyperventilation'],
                ['id' => 242, 'name' => 'respiratory muscle weakness'],
                ['id' => 243, 'name' => 'pyrexia'],
                ['id' => 244, 'name' => 'electrolyte imbalance'],
                ['id' => 245, 'name' => 'asymptomatic'],
                ['id' => 246, 'name' => 'bleeding from nose'],
                ['id' => 247, 'name' => 'purpura'],
                ['id' => 248, 'name' => 'hematuria'],
                ['id' => 249, 'name' => 'backache'],
                ['id' => 250, 'name' => 'internal bleeding'],
                ['id' => 251, 'name' => 'muscle weakness'],
                ['id' => 252, 'name' => 'ECG changes'],
                ['id' => 253, 'name' => 'hoarse voice'],
                ['id' => 254, 'name' => 'pneumonitis'],
                ['id' => 255, 'name' => 'dermatitis'],
                ['id' => 256, 'name' => 'salaivation'],
                ['id' => 257, 'name' => 'methaemoglobinaemia'],
                ['id' => 258, 'name' => 'hypoxemia'],
                ['id' => 259, 'name' => 'seizures'],
                ['id' => 260, 'name' => 'enlarged liver'],
                ['id' => 261, 'name' => 'oral ulceration'],
                ['id' => 262, 'name' => 'hematemesis'],
                ['id' => 263, 'name' => 'renal impairment'],
                ['id' => 264, 'name' => 'hepatic impairment'],
                ['id' => 265, 'name' => 'aspiration pneumonia'],
                ['id' => 266, 'name' => 'encephalopathy'],
                ['id' => 267, 'name' => 'itching'],
                ['id' => 268, 'name' => 'irritation'],
                ['id' => 269, 'name' => 'photodermatitis'],
                ['id' => 270, 'name' => 'hypothermia'],
                ['id' => 271, 'name' => 'providing sedation'],
                ['id' => 272, 'name' => 'arrhythmias'],
                ['id' => 273, 'name' => 'irritation of oral mucosa'],
                ['id' => 274, 'name' => 'tremors'],
                ['id' => 275, 'name' => 'increased muscle tone'],
                ['id' => 276, 'name' => 'uncoordinated movements'],
                ['id' => 277, 'name' => 'skin blisters'],
                ['id' => 278, 'name' => 'blood stained vomitus'],
                ['id' => 279, 'name' => 'tremar'],
                ['id' => 280, 'name' => 'myoclonus'],
                ['id' => 281, 'name' => 'motor sensory palsy'],
                ['id' => 282, 'name' => 'visual disturbance'],
                ['id' => 283, 'name' => 'slurred speech'],
                ['id' => 284, 'name' => 'optic neuropathy'],
                ['id' => 285, 'name' => 'cerebellar dysfunction'],
                ['id' => 286, 'name' => 'restless'],
                ['id' => 287, 'name' => 'methemoglobinemia'],
                ['id' => 288, 'name' => 'jaundice'],
                ['id' => 289, 'name' => 'palpitation'],
                ['id' => 290, 'name' => 'fatigue'],
                ['id' => 291, 'name' => 'dysarthria'],
                ['id' => 292, 'name' => 'eye irritation'],
                ['id' => 293, 'name' => 'wheezing'],
                ['id' => 294, 'name' => 'crepitations'],
                ['id' => 295, 'name' => 'tingling sensation'],
                ['id' => 296, 'name' => 'ventricular tachycardia'],
                ['id' => 297, 'name' => 'distal muscle paralysis'],
                ['id' => 298, 'name' => 'melaena'],
                ['id' => 299, 'name' => 'chest tightness'],
                ['id' => 300, 'name' => 'stomatitis'],
                ['id' => 301, 'name' => 'bleeding tendencies'],
                ['id' => 302, 'name' => 'dysrhythmias'],
                ['id' => 303, 'name' => 'respiratory alkalosis'],
                ['id' => 304, 'name' => 'anemia'],
                ['id' => 305, 'name' => 'gastrointestinal irritation'],
                ['id' => 306, 'name' => 'stupor'],
                ['id' => 307, 'name' => 'acidosis'],
                ['id' => 308, 'name' => 'swelling of oral mucosa'],
                ['id' => 309, 'name' => 'excitability'],
                ['id' => 310, 'name' => 'numbness'],
                ['id' => 311, 'name' => 'hypersensitivity pneumonitis'],
                ['id' => 312, 'name' => 'patchy lung infiltration'],
                ['id' => 313, 'name' => 'peripheral neuropathy'],
                ['id' => 314, 'name' => 'muscle atrophy'],
                ['id' => 315, 'name' => 'choreoathetosis'],
                ['id' => 316, 'name' => 'cardiac failure'],
                ['id' => 317, 'name' => 'allergic reactions'],
                ['id' => 318, 'name' => 'CNS effects'],
                ['id' => 319, 'name' => 'respiratory acidosis'],
                ['id' => 320, 'name' => 'anorexia'],
                ['id' => 321, 'name' => 'muscular weakness'],
                ['id' => 322, 'name' => 'shocle'],
                ['id' => 323, 'name' => 'difficulty in micturition'],
                ['id' => 324, 'name' => 'per rectal bleeding'],
                ['id' => 325, 'name' => 'gummy nose'],
                ['id' => 326, 'name' => 'vf'],
                ['id' => 327, 'name' => 'vt(torsades de pointes)'],
                ['id' => 328, 'name' => 'qt prolongation'],
                ['id' => 329, 'name' => 'ventricular ectopic beats'],
                ['id' => 330, 'name' => 'gum bleeding'],
                ['id' => 331, 'name' => 'petechiae'],
                ['id' => 332, 'name' => 'nervousness'],
                ['id' => 333, 'name' => 'bruises'],
                ['id' => 334, 'name' => 'insonnia'],
                ['id' => 335, 'name' => 'intracranial haemorrhages'],
                ['id' => 336, 'name' => 'proteinuria'],
                ['id' => 337, 'name' => 'haemorrhage'],
                ['id' => 338, 'name' => 'tinnitus'],
                ['id' => 339, 'name' => 'deafness'],
                ['id' => 340, 'name' => 'swelling of laryngeal mucosa'],
                ['id' => 341, 'name' => 'gastric irritation'],
                ['id' => 342, 'name' => 'irritability'],
                ['id' => 343, 'name' => 'hypoprothrombinemia'],
                ['id' => 344, 'name' => 'hypokalemia'],
                ['id' => 345, 'name' => 'hypernatraemia'],
                ['id' => 346, 'name' => 'hyponatremia'],
                ['id' => 347, 'name' => 'tetany'],
                ['id' => 348, 'name' => 'petechial haemorrhage'],
                ['id' => 349, 'name' => 'burning sensation of throat'],
                ['id' => 350, 'name' => 'burning sensation of chest'],
                ['id' => 351, 'name' => 'burning sensation of abdomen'],
                ['id' => 352, 'name' => '1st degree heart block'],
                ['id' => 353, 'name' => '2nd degree heart block'],
                ['id' => 354, 'name' => 'hemoglobinuria'],
                ['id' => 355, 'name' => 'ecchymoses'],
                ['id' => 356, 'name' => 'cerebral oedema'],
                ['id' => 357, 'name' => 'coria'],
                ['id' => 358, 'name' => 'noncardiogenic pulmonary vedera'],
                ['id' => 359, 'name' => 'disseminated intravascular coagulation'],
                ['id' => 360, 'name' => 'vertigo'],
                ['id' => 361, 'name' => 'rapid'],
                ['id' => 362, 'name' => 'muscle necrosis'],
                ['id' => 363, 'name' => 'cold extremities'],
                ['id' => 364, 'name' => 'burning sensation of lips'],
                ['id' => 365, 'name' => 'pustular papillae'],
                ['id' => 366, 'name' => 'ulcer'],
                ['id' => 367, 'name' => 'dark coloured urine'],
                ['id' => 368, 'name' => 'weak pulse'],
                ['id' => 369, 'name' => 'reduced urine output'],
                ['id' => 370, 'name' => 'gross haematuria'],
                ['id' => 371, 'name' => 'dysuria'],
                ['id' => 372, 'name' => 'mucosal erosion'],
                ['id' => 373, 'name' => 'renal dysfunction'],
                ['id' => 374, 'name' => 'hypoglycaemia'],
                ['id' => 375, 'name' => 'priapism'],
                ['id' => 376, 'name' => 'cardiac abnormalities'],
                ['id' => 377, 'name' => 'vaginal bleeding'],
                ['id' => 378, 'name' => 'occult rectal bleeding'],
                ['id' => 379, 'name' => 'lsb_release -a'],
                ['id' => 380, 'name' => 'cranial nerve palsy'],
                ['id' => 381, 'name' => 'progressive muscle weakness'],
                ['id' => 382, 'name' => 'periorbital dermatitis'],
                ['id' => 383, 'name' => 'keratoconjunctivitis'],
                ['id' => 384, 'name' => 'bullous skin lesions'],
                ['id' => 385, 'name' => 'dry flushed skin'],
                ['id' => 386, 'name' => 'decreased bowel sounds'],
                ['id' => 387, 'name' => 'incoherent speech'],
                ['id' => 388, 'name' => 'gastrointestinal disturbances'],
                ['id' => 389, 'name' => 'loss of short term memory'],
                ['id' => 390, 'name' => 'frank psychosis'],
                ['id' => 391, 'name' => 'mild hypotension'],
                ['id' => 392, 'name' => 'impaired consciousness'],
                ['id' => 393, 'name' => 'irritant to skin'],
                ['id' => 394, 'name' => 'irritant to eyes'],
                ['id' => 395, 'name' => 'sharp burning sensation of mouth '],
                ['id' => 396, 'name' => 'sharp burning sensation of abdomen'],
                ['id' => 397, 'name' => 'hyperglycaemia'],
                ['id' => 398, 'name' => 'nephrotic syndrome'],
                ['id' => 399, 'name' => '3rd degree heart block'],
                ['id' => 400, 'name' => 'asystole'],
                ['id' => 401, 'name' => 'depression of myocardial contractility'],
                ['id' => 402, 'name' => 'neurological effects'],
                ['id' => 403, 'name' => 'gaze palsies'],
                ['id' => 404, 'name' => 'intention tremor'],
                ['id' => 405, 'name' => 'conduction defects in heart'],
                ['id' => 406, 'name' => 'complete heart block'],
                ['id' => 407, 'name' => 'dystonic reactions'],
                ['id' => 408, 'name' => 'disorders in mood'],
                ['id' => 409, 'name' => 'cognitive functions'],
                ['id' => 410, 'name' => 'heparin failure'],
                ['id' => 411, 'name' => 'elevated creatine kinase'],
                ['id' => 412, 'name' => 'hepatic enzymes'],
                ['id' => 413, 'name' => 'delay in gastric emptying'],
                ['id' => 414, 'name' => 'perforation'],
                ['id' => 415, 'name' => 'gastrointestinal haemorrhage'],
                ['id' => 416, 'name' => 'lethargy'],
                ['id' => 417, 'name' => 'elevated hepatic enzymes'],
                ['id' => 418, 'name' => 'albuminuria'],
                ['id' => 419, 'name' => 'discoloration of urine'],
                ['id' => 420, 'name' => 'cardiogenic shock'],
                ['id' => 421, 'name' => 'cardiac arrest'],
                ['id' => 422, 'name' => 'sudden apnoea'],
                ['id' => 423, 'name' => 'cheyne stokes breathing'],
                ['id' => 424, 'name' => 'vagiral withdrawal bleeding in prepubertal girts'],
                ['id' => 425, 'name' => 'retention of urine'],
                ['id' => 426, 'name' => 'myoclonic twitching'],
                ['id' => 427, 'name' => 'generalized convulsions'],
                ['id' => 428, 'name' => 'ophthalmoplegia'],
                ['id' => 429, 'name' => 'torsade de pointes'],
                ['id' => 430, 'name' => 'conduction defects '],
                ['id' => 431, 'name' => 'prolonged QRS interval'],
                ['id' => 432, 'name' => 'supraventricular dysrhythmias'],
                ['id' => 433, 'name' => 'long QT interval syndrome (LQTS)'],
                ['id' => 434, 'name' => 'adult respiratory distress syndrome'],
                ['id' => 435, 'name' => 'blisters over pressure points'],
                ['id' => 436, 'name' => 'gastrointestinal bleeding'],

            ]
        );
    }
}
